name: Deploy Producao

on:
  workflow_dispatch:
    inputs:
      fresh-deploy:
        description: 'Limpa por completo o ambiente de produção antes de fazer o deploy'
        required: false
        default: 'false'
        type: boolean
  push:
    branches:
      - main
jobs:
  Deploy-Producao:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup SSH Connection
      env:
        SSH_USER: ${{ secrets.SERVER_USER }}
        SSH_KEY: ${{ secrets.SERVER_KEY }}
        SSH_HOST: ${{ secrets.SERVER_HOST }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        cat >>~/.ssh/config <<END
        Host producao-host
          HostName $SSH_HOST
          User $SSH_USER
          Port $SSH_PORT
          IdentityFile ~/.ssh/id_rsa
          StrictHostKeyChecking no
        END

    - name: Limpando Servidor
      if: ${{ github.event.inputs.fresh-deploy == 'true' }}
      continue-on-error: true
      env:
        DB_USER: ${{ secrets.SERVER_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
      run: |
        ssh producao-host "sudo systemctl stop prod_laravel_worker.service"
        ssh producao-host "sudo rm -rf /var/www/atomic.sec/producao/*"
        ssh producao-host "mysql -u $DB_USER -p$DB_PASS -e 'DROP DATABASE producao; CREATE DATABASE producao;'"


    - name: Build Assets
      run: |
        cd /home/runner/work/AtomicSec/AtomicSec/Atomic/
        npm install
        npm run build
        cd /home/runner/work/AtomicSec/AtomicSec/

    - name: Build and send AnalyzerAgent
      run: |
        cd /home/runner/work/AtomicSec/AtomicSec/AnalyzerAgent/
        docker build -t "analyzeragent:latest" .
        docker save -o analyzeragent-latest.tar analyzeragent:latest
        scp ./analyzeragent-latest.tar producao-host:~/analyzeragent-latest.tar
        ssh producao-host "docker load -i ~/analyzeragent-latest.tar && rm ~/analyzeragent-latest.tar"

    - name: Build and set up HTTP Keep Alive Attack
      run: |
        sudo apt install golang-go
        mkdir -p /home/runner/work/AtomicSec/AtomicSec/Atomic/bin/attacks
        cd /home/runner/work/AtomicSec/AtomicSec/Attacks/HTTP_Keep-Alive/
        GOOS=linux GOARCH=amd64 go build -o HTTP_Keep_Alive
        cp ./HTTP_Keep_Alive /home/runner/work/AtomicSec/AtomicSec/Atomic/bin/attacks/

    - name: Build and set up HTTP Slow Post Attack
      run: |
        cd /home/runner/work/AtomicSec/AtomicSec/Attacks/HTTP_Slow-Post/
        GOOS=linux GOARCH=amd64 go build -o HTTP_Slow_Post
        cp ./HTTP_Slow_Post /home/runner/work/AtomicSec/AtomicSec/Atomic/bin/attacks/

    - name: Build and set up Post Flood Attack
      run: |
        cd /home/runner/work/AtomicSec/AtomicSec/Attacks/Post_Flood
        GOOS=linux GOARCH=amd64 go build -o Post_Flood
        cp ./Post_Flood /home/runner/work/AtomicSec/AtomicSec/Atomic/bin/attacks/

    - name: Web platform sync files
      run: |
        rsync -z \
              --delete \
              --inplace \
              --no-perms \
              --recursive \
              --whole-file \
              --exclude='.git' \
              --exclude='.github' \
              --exclude='node_modules' \
              --exclude='vendor' \
              --include='storage/framework' \
              --exclude='storage/*' \
              --exclude='.env' \
              /home/runner/work/AtomicSec/AtomicSec/Atomic/ producao-host:/var/www/atomic.sec/producao/

    - name: Setup web platform
      env:
        SSH_USER: ${{ secrets.SERVER_USER }}
        ENV_PRODUCAO: ${{ secrets.ENV_PRODUCAO }}
      run: |
        #Setup .env
        echo "$ENV_PRODUCAO" > env_producao
        ssh producao-host "rm /var/www/atomic.sec/producao/.env"
        scp ./env_producao producao-host:/var/www/atomic.sec/producao/.env
        rm ./env_producao
        #Install composer dependencies
        ssh producao-host "cd /var/www/atomic.sec/producao/ && composer install --no-dev --optimize-autoloader"
        #Make results directory
        ssh producao-host "mkdir -p /var/www/atomic.sec/producao/storage/framework/cache/data"
        #set permissions
        ssh producao-host "sudo chown www-data:www-data -R /var/www/atomic.sec/producao/"
        ssh producao-host "sudo chmod 775 -R /var/www/atomic.sec/producao/"
        #Setup attack permissions
        ssh producao-host "sudo chmod +x -R /var/www/atomic.sec/producao/bin/attacks/HTTP_Keep_Alive"
        ssh producao-host "sudo systemctl restart prod_laravel_worker.service"

    - name: Setup again
      if: ${{ github.event.inputs.fresh-deploy == 'true' }}
      run: |
        ssh producao-host "cd /var/www/atomic.sec/producao/ && php artisan migrate --force"
        ssh producao-host "cd /var/www/atomic.sec/producao/ && php artisan config:cache"
        ssh producao-host "cd /var/www/atomic.sec/producao/ && php artisan route:cache"
        ssh producao-host "cd /var/www/atomic.sec/producao/ && php artisan view:cache"
        ssh producao-host "cd /var/www/atomic.sec/producao/ && php artisan storage:link"
        ssh producao-host "cd /var/www/atomic.sec/producao/ && php artisan queue:restart"
        #Make results directory
        ssh producao-host "mkdir -p /var/www/atomic.sec/producao/storage/framework/cache/data"
        #set permissions
        ssh producao-host "sudo chown www-data:www-data -R /var/www/atomic.sec/producao/"
        ssh producao-host "sudo chmod 775 -R /var/www/atomic.sec/producao/"
        #Setup attack permissions
        ssh producao-host "sudo chmod +x -R /var/www/atomic.sec/producao/bin/attacks/HTTP_Keep_Alive"
        ssh producao-host "sudo systemctl restart prod_laravel_worker.service"